In [19]:
import numpy as np
import matplotlib.pyplot as plt

# Recurrent neural network

- used with sequential data (time series, sentences...)

- parameters: input weights $\mathbf{W}_i$, hidden weights $\mathbf{W}_h$ and output weights $\mathbf{W}_o$

# Forward pass

$$\mathbf{z}_t = \mathbf{h}_{t-1} \cdot \mathbf{W}_h + \mathbf{x} \cdot \mathbf{W}_i + \mathbf{b}_i$$
$$\mathbf{h}_{t} = \phi(\mathbf{z}_t)$$
$$\mathbf{y}_t = \mathbf{h}_{t} \cdot \mathbf{W}_o + \mathbf{b}_o$$

# Gradients

$$\frac{\partial \mathbf{z}_t}{\partial \mathbf{h}_{t-1}} = \mathbf{W}_h \quad \quad \frac{\partial \mathbf{z}_t}{\partial \mathbf{W}_h} = \mathbf{h}_{t-1} \quad \quad \frac{\partial \mathbf{z}_t}{\partial \mathbf{x}} = \mathbf{W}_i \quad \quad \frac{\partial \mathbf{z}_t}{\partial \mathbf{W}_i} = \mathbf{x} \quad \quad \frac{\partial \mathbf{z}_t}{\partial \mathbf{b}_i} = 1$$

$$\frac{\partial \mathbf{h}_t}{\partial \mathbf{z}_t} = \phi'(\mathbf{z}_t)$$

$$\frac{\partial \mathbf{y}_t}{\partial \mathbf{h}_{t}} = \mathbf{W}_o \quad \quad \frac{\partial \mathbf{y}_t}{\partial \mathbf{W}_o} = \mathbf{h}_{t} \quad \quad \frac{\partial \mathbf{y}_t}{\partial \mathbf{b}_o} = 1$$

# Backward pass


$$
\begin{align*}

\begin{aligned}
\frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_o} &= \frac{\partial \mathcal{L}_t}{\partial \mathbf{y}_t} \cdot \frac{\partial \mathbf{y}_t}{\partial \mathbf{W}_o} \\
&= \delta_t \cdot \mathbf{h}_t
\end{aligned} \quad \quad

\begin{aligned}
\frac{\partial \mathcal{L}}{\partial \mathbf{W}_o} = \sum_t \frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_o}
\end{aligned}

\end{align*}
$$

$$
\begin{align*}


\begin{aligned}

\frac{\partial \mathcal{L}_t}{\partial \mathbf{b}_o} &= \frac{\partial \mathcal{L}_t}{\partial \mathbf{y}_t} \cdot \frac{\partial \mathbf{y}_t}{\partial \mathbf{b}_o} \\
&= \delta_t \cdot 1 \\
&= \delta_t

\end{aligned} \quad \quad


\begin{aligned}

\frac{\partial \mathcal{L}}{\partial \mathbf{b}_o} = \sum_t \frac{\partial \mathcal{L}_t}{\partial \mathbf{b}_o}

\end{aligned}


\end{align*}
$$

$$ 

\begin{align*}

\begin{aligned}

\frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_h} &= \left( \frac{\partial \mathcal{L}_t}{\partial \mathbf{y}_t} \cdot \frac{\partial \mathbf{y}_t}{\partial \mathbf{h}_{t}} + \mathbf{g}_{t+1} \cdot \frac{\partial \mathbf{z}_{t+1}}{\partial \mathbf{h}_{t}} \right) \cdot \frac{\partial \mathbf{h}_t}{\partial \mathbf{z}_t} \cdot \frac{\partial \mathbf{z}_t}{\partial \mathbf{W}_h} \\

&= \left( \delta_t \cdot \mathbf{W}_o + \mathbf{g}_{t+1} \cdot \mathbf{W}_h \right) \cdot \phi'(\mathbf{z}_t)\cdot \mathbf{h}_{t-1} \\

&= \left[\mathbf{d}_t \odot \phi'(\mathbf{z}_t) \right] \cdot \mathbf{h}_{t-1} \\

&= \mathbf{g}_t \cdot \mathbf{h}_{t-1}

\end{aligned} \quad \quad

\begin{aligned}
\frac{\partial \mathcal{L}}{\partial \mathbf{W}_h} = \sum_t \frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_h}
\end{aligned}

\end{align*}
$$

$$ 

\begin{align*}

\begin{aligned}

\frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_i} &= \left( \frac{\partial \mathcal{L}_t}{\partial \mathbf{y}_t} \cdot \frac{\partial \mathbf{y}_t}{\partial \mathbf{h}_{t}} + \mathbf{g}_{t+1} \cdot \frac{\partial \mathbf{z}_{t+1}}{\partial \mathbf{h}_{t}} \right) \cdot \frac{\partial \mathbf{h}_t}{\partial \mathbf{z}_t} \cdot \frac{\partial \mathbf{z}_t}{\partial \mathbf{W}_i} \\

&= \left( \delta_t \cdot \mathbf{W}_o + \mathbf{g}_{t+1} \cdot \mathbf{W}_h \right) \cdot \phi'(\mathbf{z}_t)\cdot \mathbf{x}_{t} \\

&= \left[\mathbf{d}_t \odot \phi'(\mathbf{z}_t) \right] \cdot \mathbf{x}_{t} \\

&= \mathbf{g}_t \cdot \mathbf{x}_{t}

\end{aligned} \quad \quad

\begin{aligned}
\frac{\partial \mathcal{L}}{\partial \mathbf{W}_i} = \sum_t \frac{\partial \mathcal{L}_t}{\partial \mathbf{W}_i}
\end{aligned}

\end{align*}
$$

$$ 

\begin{align*}

\begin{aligned}

\frac{\partial \mathcal{L}_t}{\partial \mathbf{b}_i} &= \left( \frac{\partial \mathcal{L}_t}{\partial \mathbf{y}_t} \cdot \frac{\partial \mathbf{y}_t}{\partial \mathbf{h}_{t}} + \mathbf{g}_{t+1} \cdot \frac{\partial \mathbf{z}_{t+1}}{\partial \mathbf{h}_{t}} \right) \cdot \frac{\partial \mathbf{h}_t}{\partial \mathbf{z}_t} \cdot \frac{\partial \mathbf{z}_t}{\partial \mathbf{b}_i} \\

&= \left( \delta_t \cdot \mathbf{W}_o + \mathbf{g}_{t+1} \cdot \mathbf{W}_h \right) \cdot \phi'(\mathbf{z}_t)\cdot 1 \\

&= \mathbf{d}_t \odot \phi'(\mathbf{z}_t) \\

&= \mathbf{g}_t

\end{aligned} \quad \quad

\begin{aligned}
\frac{\partial \mathcal{L}}{\partial \mathbf{b}_i} = \sum_t \frac{\partial \mathcal{L}_t}{\partial \mathbf{b}_i}
\end{aligned}

\end{align*}
$$

In [20]:
class RecurrentLayer:

    def __init__(self, n_inputs: int, n_hidden: int, n_outputs: int):
        k = 1/np.sqrt(n_hidden)
        self.n_hidden = n_hidden
        self.input_weights = np.random.rand(n_inputs, n_hidden) * 2 * k - k
        self.hidden_weights = np.random.rand(n_hidden, n_hidden) * 2 * k - k
        self.output_weights = np.random.rand(n_hidden, n_outputs) * 2 * k - k
        self.output_bias = np.random.rand(n_outputs) * 2 * k - k
        self.input_bias = np.random.rand(n_hidden) * 2 * k - k
        
    def forward(self, inputs: np.ndarray):
        self.inputs = inputs
        self.n_samples = inputs.shape[0]
        self.output = np.zeros((self.n_samples, self.output_weights.shape[1]))
        self.hidden_states = np.zeros((self.n_samples, self.n_hidden))

        for idx, x in enumerate(inputs):

            x = x.reshape(1, -1)

            input_x = np.dot(x, self.input_weights)

            hidden_x = input_x + np.dot(self.hidden_states[max(idx-1, 0)], self.hidden_weights) + self.input_bias
            hidden_x = np.tanh(hidden_x)
            self.hidden_states[idx] = hidden_x.copy()

            output_x = np.dot(hidden_x, self.output_weights) + self.output_bias
            self.output[idx] = output_x.copy()

    def backward(self, delta: np.ndarray):

        self.dinput_weights = np.zeros_like(self.input_weights)
        self.dhidden_weights = np.zeros_like(self.hidden_weights)
        self.dinput_bias = np.zeros_like(self.input_bias)
        self.doutput_weights = np.zeros_like(self.output_weights)
        self.doutput_bias = np.zeros_like(self.output_bias)
        self.dinputs = np.zeros_like(self.inputs, dtype=np.float64)
        next_hidden = None

        for t in range(self.n_samples - 1, -1, -1):

            loss_gradient = delta[t].reshape(1, -1)
            hidden_state = self.hidden_states[t].reshape(-1, 1)

            self.doutput_weights += np.dot(hidden_state, loss_gradient)
            self.doutput_bias += loss_gradient.reshape(-1)

            hidden_gradient = np.dot(loss_gradient, self.output_weights.T)
            if next_hidden is not None:
                hidden_gradient += np.dot(next_hidden, self.hidden_weights.T)

            dtanh = 1 - self.hidden_states[t]**2
            hidden_gradient *= dtanh

            next_hidden = hidden_gradient.copy()

            if t > 0:
                self.dhidden_weights += np.dot(self.hidden_states[t-1].reshape(-1, 1), hidden_gradient)

            self.dinput_weights += np.dot(self.inputs[t].reshape(-1, 1), hidden_gradient)
            self.dinput_bias += hidden_gradient.reshape(-1)
            
            self.dinputs[t] += np.dot(self.input_weights, hidden_gradient.T).reshape(-1)

In [21]:
def mse_grad(y_pred, y_true):
    return (y_pred - y_true)

def mse_loss(y_pred, y_true):
    return np.mean(0.5 * (y_pred - y_true)**2)

In [22]:
def update_recurrent_layer(layer, lr, momentum=0.9):
    """layer.input_weights += -lr * layer.dinput_weights
    layer.hidden_weights += -lr * layer.dhidden_weights
    layer.hidden_biases += -lr * layer.dhidden_biases
    layer.output_weights += -lr * layer.doutput_weights
    layer.output_bias += -lr * layer.doutput_bias"""

    if momentum:

        if not hasattr(layer, 'input_weights_momentum'):
            layer.input_weights_momentum = np.zeros_like(layer.input_weights)
            layer.hidden_weights_momentum = np.zeros_like(layer.hidden_weights)
            layer.output_weights_momentum = np.zeros_like(layer.output_weights)
            layer.output_bias_momentum = np.zeros_like(layer.output_bias)
            layer.input_bias_momentum = np.zeros_like(layer.input_bias)

        layer.input_weights_momentum = momentum * layer.input_weights_momentum - lr * layer.dinput_weights
        dinput_weights_updates = layer.input_weights_momentum

        layer.hidden_weights_momentum = momentum * layer.hidden_weights_momentum - lr * layer.dhidden_weights
        dhidden_weights_updates = layer.hidden_weights_momentum

        layer.output_weights_momentum = momentum * layer.output_weights_momentum - lr * layer.doutput_weights
        doutput_weights_updates = layer.output_weights_momentum

        layer.output_bias_momentum = momentum * layer.output_bias_momentum - lr * layer.doutput_bias
        doutput_bias_updates = layer.output_bias_momentum

        layer.input_bias_momentum = momentum * layer.input_bias_momentum - lr * layer.dinput_bias
        dinput_bias_updates = layer.input_bias_momentum


    else:

        dinput_weights_updates = - lr * layer.dinput_weights

        dhidden_weights_updates =  -lr * layer.dhidden_weights

        doutput_weights_updates = - lr * layer.doutput_weights

        doutput_bias_updates = - lr * layer.doutput_bias

        dinput_bias_updates = - lr * layer.dinput_bias

    layer.input_weights += dinput_weights_updates
    layer.hidden_weights += dhidden_weights_updates
    layer.input_bias += dinput_bias_updates
    layer.output_weights += doutput_weights_updates
    layer.output_bias += doutput_bias_updates

In [23]:
# seed 0, lr=5e-4, backward konvergira
from sklearn.preprocessing import StandardScaler

np.random.seed(0)

rec11 = RecurrentLayer(1, 5, 1)
rec21 = RecurrentLayer(1, 7, 1)

rec12 = RecurrentLayer(1, 5, 1)
rec22 = RecurrentLayer(1, 7, 1)

sequence = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)
scaler = StandardScaler()
sequence = scaler.fit_transform(sequence)
result = np.array([60, 52, 52, 53, 52, 50, 52, 56, 54, 57]).reshape(-1, 1)
lr = 5e-3
seq_len = 3

for i in range(500):

    for j in range(len(sequence)-seq_len):

        rec11.forward(sequence[j:j+seq_len, :])
        rec21.forward(rec11.output)

        rec12.forward(sequence[j:j+seq_len, :])
        rec22.forward(rec12.output)

        loss_grad_1 = mse_grad(rec21.output.reshape(-1, 1), result[j:j+seq_len, :])
        loss_grad_2 = mse_grad(rec22.output.reshape(-1, 1), result[j:j+seq_len, :])

        rec21.backward(loss_grad_1)
        rec11.backward(rec21.dinputs)

        rec22.backward(loss_grad_2)
        rec12.backward(rec22.dinputs)

        """if i % 1000 == 0:
            norme11 = []
            norme12 = []
            norme21 = []
            norme22 = []
            for l in [rec11.input_weights, 
                    rec11.hidden_weights, 
                    rec11.output_weights, 
                    rec11.output_bias, 
                    rec11.hidden_biases, 
                    rec11.hidden_states]:
                norme11.append(np.linalg.norm(l))

            for l in [rec12.input_weights, 
                    rec12.hidden_weights, 
                    rec12.output_weights, 
                    rec12.output_bias, 
                    rec12.hidden_biases, 
                    rec12.hidden_states]:
                norme12.append(np.linalg.norm(l))

            for l in [rec21.input_weights, 
                    rec21.hidden_weights, 
                    rec21.output_weights, 
                    rec21.output_bias, 
                    rec21.hidden_biases, 
                    rec21.hidden_states]:
                norme21.append(np.linalg.norm(l))

            for l in [rec22.input_weights, 
                    rec22.hidden_weights, 
                    rec22.output_weights, 
                    rec22.output_bias, 
                    rec22.hidden_biases, 
                    rec22.hidden_states]:
                norme22.append(np.linalg.norm(l))

            norme11 = np.array(norme11)
            norme12 = np.array(norme12)
            norme21 = np.array(norme21)
            norme22 = np.array(norme22)

            print(f'Razlike 1: {np.abs(norme11 - norme12)}')
            print(f'Razlike 2: {np.abs(norme21 - norme22)}')"""

        update_recurrent_layer(rec11, lr, momentum=0)
        update_recurrent_layer(rec12, lr, momentum=0)
        update_recurrent_layer(rec21, lr, momentum=0)
        update_recurrent_layer(rec22, lr, momentum=0)

    #print(f'dInput weights: {np.linalg.norm(rec11.dinput_weights)}, dhidden weights: {np.linalg.norm(rec11.dhidden_weights)}, doutput weights: {np.linalg.norm(rec11.doutput_weights)}')
    #print(f'dInput weights: {np.linalg.norm(rec12.dinput_weights)}, dhidden weights: {np.linalg.norm(rec12.dhidden_weights)}, doutput weights: {np.linalg.norm(rec12.doutput_weights)}')

    if i % 100 == 0:
        print(f'Loss 1: {mse_loss(rec21.output.reshape(-1, 1), result[j:j+seq_len, :])}')
        print(f'Loss 2: {mse_loss(rec22.output.reshape(-1, 1), result[j:j+seq_len, :])}')

rec11.forward(sequence)
rec21.forward(rec11.output)
print(rec21.output.reshape(-1))
print(result.reshape(-1))

rec12.forward(sequence)
rec22.forward(rec12.output)
print(rec22.output.reshape(-1))
print(result.reshape(-1))

Loss 1: 641.4295974443879
Loss 2: 582.2808127930862
Loss 1: 2.278011331045261
Loss 2: 2.356390502453872
Loss 1: 2.244332611170712
Loss 2: 2.2603650494965044
Loss 1: 2.242822600390181
Loss 2: 2.252173115395604
Loss 1: 2.236721500567034
Loss 2: 2.2464579462336025
[52.86525189 52.93442906 52.93389858 52.9336197  52.93332997 52.93295864
 52.93248346 52.93188872 52.93113802 52.93017165]
[60 52 52 53 52 50 52 56 54 57]
[52.85779326 52.92445304 52.92346299 52.92434006 52.9245707  52.92409876
 52.92292779 52.92115118 52.9185935  52.91504262]
[60 52 52 53 52 50 52 56 54 57]


In [24]:
import pandas as pd

data = pd.read_csv('clean_weather.csv', names=['date', 'tmax', 'tmin', 'rain', 'tmax_tomorrow'], header=0)
data

date  tmax  tmin  rain  tmax_tomorrow
0      1970-01-01  60.0  35.0   0.0           52.0
1      1970-01-02  52.0  39.0   0.0           52.0
2      1970-01-03  52.0  35.0   0.0           53.0
3      1970-01-04  53.0  36.0   0.0           52.0
4      1970-01-05  52.0  35.0   0.0           50.0
...           ...   ...   ...   ...            ...
13504  2022-11-22  62.0  35.0   0.0           67.0
13505  2022-11-23  67.0  38.0   0.0           66.0
13506  2022-11-24  66.0  41.0   0.0           70.0
13507  2022-11-25  70.0  39.0   0.0           62.0
13508  2022-11-26  62.0  41.0   0.0           64.0

[13509 rows x 5 columns]

In [25]:
from sklearn.preprocessing import StandardScaler

FEATURES = ['tmax', 'tmin', 'rain']
TARGET = 'tmax_tomorrow'

X = data[FEATURES].to_numpy()
y = data[TARGET].to_numpy()

scaler = StandardScaler()
X = scaler.fit_transform(X)

print(f'X: {X.shape}')
print(f'y: {y.shape}')

X: (13509, 3)
y: (13509,)


In [26]:
threshold = 0.05

X_train = X[:int(threshold*len(X)),:].copy()
y_train = y[:int(threshold*len(X))].copy()

X_test = X[int(threshold*len(X)):,:].copy()
y_test = y[int(threshold*len(X)):].copy()

print(f'X_train: {X_train.shape}, y_train: {y_train.shape}')
print(f'X_test: {X_test.shape}, y_test: {y_test.shape}')

X_train: (675, 3), y_train: (675,)
X_test: (12834, 3), y_test: (12834,)


In [27]:
np.random.seed(0)
rec1 = RecurrentLayer(3, 4, 1)

lr = 1e-3
seq_len = 7

for i in range(51):

    epoch_loss = 0

    for j in range(len(X_train) - seq_len):

        rec1.forward(X_train[j:j+seq_len, :])

        epoch_loss += mse_loss(rec1.output, y_train[j:j+seq_len])

        loss_grad = mse_grad(rec1.output.reshape(-1), y_train[j:j+seq_len])

        rec1.backward(loss_grad)

        update_recurrent_layer(rec1, lr, momentum=0.)

    if i % 10 == 0:
        print(f'Epoch loss {i}: {epoch_loss / len(X_train)}')

    print(f'dInput weights: {np.linalg.norm(rec1.dinput_weights)}, dhidden weights: {np.linalg.norm(rec1.dhidden_weights)}, doutput weights: {np.linalg.norm(rec1.doutput_weights)}')

Epoch loss 0: 59.36530548954579
dInput weights: 9.23545522609929, dhidden weights: 0.1513727467003833, doutput weights: 28.82272775042941
dInput weights: 11.345237196157536, dhidden weights: 0.15317013284321307, doutput weights: 28.640884976196464
dInput weights: 22.20137239826506, dhidden weights: 11.01622715347365, doutput weights: 24.899365387596344
dInput weights: 208.3497272776964, dhidden weights: 265.9011302523748, doutput weights: 48.020292475543805
dInput weights: 199.9357852803011, dhidden weights: 260.83423880394275, doutput weights: 33.099591390073336
dInput weights: 8.717254557444894, dhidden weights: 14.40671154896009, doutput weights: 1.8139007252136974
dInput weights: 11.182873516487751, dhidden weights: 23.661544066362083, doutput weights: 2.068362157527905
dInput weights: 20.82655503467082, dhidden weights: 43.00056654070374, doutput weights: 4.355895308117471
dInput weights: 25.260385598948407, dhidden weights: 54.335149147697955, doutput weights: 5.3328379391260015


In [34]:
from random import randint

start = randint(0, len(X_test))
seq_len = 4
rec1.forward(X_test[start:start+seq_len, :])
print(rec1.output.reshape(-1))
print(y_test.reshape(-1)[start:start+seq_len])
print(f'Loss: {mse_loss(rec1.output.reshape(-1), y_test.reshape(-1)[start:start+seq_len])}')

[64.15515683 67.01852578 62.59179562 65.16812513]
[65. 62. 63. 67.]
Loss: 3.6777196676920982
